name: Test

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: ghcr.io/tuna/thuthesis-test-env
    steps:
    - uses: actions/checkout@v4
    - id: vars
      run: echo "git_describe=$(git describe --tags)" >> $GITHUB_OUTPUT
    - name: Test thesis
      run: make thesis
    - name: Test spine
      run: make spine
    - name: Test doc
      run: make doc
    - name: Test with l3build
      run: make test
    - name: Build release zip with l3build
      run: l3build ctan --config build-ctan
    - name: Upload release zip
      uses: actions/upload-artifact@v4
      with:
         name: thuthesis-ctan-${{ steps.vars.outputs.git_describe }}
         path: thuthesis-ctan.zip
    - name: Upload test results if failed
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-result-${{ steps.vars.outputs.git_describe }}
        path: |
          build/test
          build/test-testfiles
