name: Test

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: 
      image: ghcr.io/tuna/thuthesis-test-env
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build documentation and example
      run: make all-dev
    - name: Upload build results
      uses: actions/upload-artifact@v4
      with:
        name: build-result
        path: |
          thuthesis.pdf
          thuthesis-example.pdf
    - name: Build release zip
      run: |
        version=$(git describe --tags)
        echo "Current git revision: $version"
        python3 create_release.py --version $version
    - name: Build CTAN release zip with l3build
      run: l3build ctan --config build-ctan
    - name: Upload release zip
      uses: actions/upload-artifact@v4
      with:
          name: thuthesis-snapshot-release
          path: |
            thuthesis-ctan.zip
            dist/thuthesis-*.zip

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: 
      image: ghcr.io/tuna/thuthesis-test-env
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - name: Test with l3build
      run: make test
    - name: Upload test results if failed
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-result
        path: |
          build/test
          build/test-testfiles
